services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: icap_db
      POSTGRES_USER: icap_user
      POSTGRES_PASSWORD: icap_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-icap_user} -d ${POSTGRES_DB:-icap_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "*"
      POSTGRES_DB: icap_db
      POSTGRES_USER: icap_user
      POSTGRES_PASSWORD: icap_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3715:5173"
    depends_on:
      - api

volumes:
  postgres_data:
