# Generated by Django 5.2.7 on 2025-10-16 08:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='類別名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '裝置類別',
                'verbose_name_plural': '裝置類別',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='序號')),
                ('name', models.CharField(max_length=200, verbose_name='裝置名稱')),
                ('status', models.CharField(choices=[('active', '使用中'), ('inactive', '閒置'), ('maintenance', '維修中'), ('retired', '已報廢')], default='active', max_length=20, verbose_name='狀態')),
                ('custom_properties', models.JSONField(blank=True, default=dict, verbose_name='自訂屬性')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='購買日期')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='成本')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='所屬部門')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='放置位置')),
                ('depreciation_rate', models.DecimalField(blank=True, decimal_places=2, help_text='年折舊率（百分比）', max_digits=5, null=True, verbose_name='折舊率')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='保固到期日')),
                ('supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='供應商')),
                ('maintenance_info', models.TextField(blank=True, null=True, verbose_name='維護資訊')),
                ('retirement_date', models.DateField(blank=True, null=True, verbose_name='報廢日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_devices', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_devices', to=settings.AUTH_USER_MODEL, verbose_name='責任人')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='device_management.devicecategory', verbose_name='裝置類別')),
            ],
            options={
                'verbose_name': '裝置',
                'verbose_name_plural': '裝置',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP 位址')),
                ('mac_address', models.CharField(help_text='格式：XX:XX:XX:XX:XX:XX', max_length=17, verbose_name='MAC 位址')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='分配日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('history', models.JSONField(blank=True, default=list, help_text='IP/MAC 異動歷史記錄', verbose_name='異動歷史')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_records', to='device_management.device', verbose_name='所屬裝置')),
            ],
            options={
                'verbose_name': 'IP 記錄',
                'verbose_name_plural': 'IP 記錄',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='屬性名稱')),
                ('field_type', models.CharField(choices=[('text', '文字'), ('number', '數字'), ('date', '日期'), ('boolean', '布林值'), ('choice', '選項')], max_length=20, verbose_name='屬性型態')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='預設值')),
                ('choices', models.JSONField(blank=True, help_text='當型態為選項時，填入可選值的 JSON 陣列', null=True, verbose_name='選項值')),
                ('help_text', models.TextField(blank=True, null=True, verbose_name='說明文字')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_definitions', to='device_management.devicecategory', verbose_name='所屬類別')),
            ],
            options={
                'verbose_name': '屬性定義',
                'verbose_name_plural': '屬性定義',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '建立'), ('update', '更新'), ('delete', '刪除'), ('view', '查看')], max_length=20, verbose_name='操作類型')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名稱')),
                ('object_id', models.CharField(max_length=100, verbose_name='物件 ID')),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True, verbose_name='物件表示')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='變更內容')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作 IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用戶代理')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用戶')),
            ],
            options={
                'verbose_name': '操作日誌',
                'verbose_name_plural': '操作日誌',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='device_mana_user_id_e2b06b_idx'), models.Index(fields=['model_name', '-timestamp'], name='device_mana_model_n_33bbbb_idx'), models.Index(fields=['action', '-timestamp'], name='device_mana_action_b3470c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='device_mana_serial__355c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='device_mana_status_4f1f81_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['department'], name='device_mana_departm_2b8835_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['location'], name='device_mana_locatio_3b74d3_idx'),
        ),
        migrations.AddIndex(
            model_name='iprecord',
            index=models.Index(fields=['ip_address'], name='device_mana_ip_addr_cab586_idx'),
        ),
        migrations.AddIndex(
            model_name='iprecord',
            index=models.Index(fields=['mac_address'], name='device_mana_mac_add_533efb_idx'),
        ),
        migrations.AddIndex(
            model_name='iprecord',
            index=models.Index(fields=['is_active'], name='device_mana_is_acti_68bd03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertydefinition',
            unique_together={('category', 'name')},
        ),
    ]
